name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        py-version: [3.10, 3.11, 3.12]
        os: [ubuntu-20.04, macos-14, windows-latest]
        exclude:
         - os: macos-14
           py-version: 3.12
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version }}
        
